title: Researcher
url: "https://mmogib.github.io" #"https://ankitsultana.com"
baseurl: "/faculty_website" # "/researcher"

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
